(PDB-5730) Update pgjdbc to 42.4.5
Resolved a bug in pgjdbc
https://github.com/pgjdbc/pgjdbc/issues/3014

which resulted in a failure in PuppetDB due to
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer

To reproduce that error you need to re-use the connection and submit
multiple catalogs until the buffer is filled.